from dataclasses import dataclass


@dataclass
class Block:
    id: str = 'air'
    state: dict[str, tuple[bool | int | str, set[bool | int | str]]] = {}


DEFAULT_BLOCKS = [
    Block('activator_rail',
          {'powered': (False, {True, False}),
           'shape': ('north_south', {'east_west', 'north_south', 'ascending_east',
                                     'ascending_north', 'ascending_south', 'ascending_west'}),
           'waterlogged': (False, {True, False})}),
    Block('small_amethyst_bud',
          {'facing': ('up', {'up', 'down', 'north',
                             'south', 'east', 'west'}),
           'waterlogged': (False, {True, False})}),
    Block('medium_amethyst_bud',
          {'facing': ('up', {'up', 'down', 'north',
                             'south', 'east', 'west'}),
           'waterlogged': (False, {True, False})}),
    Block('large_amethyst_bud',
          {'facing': ('up', {'up', 'down', 'north',
                             'south', 'east', 'west'}),
           'waterlogged': (False, {True, False})}),
    Block('amethyst_cluster',
          {'facing': ('up', {'up', 'down', 'north',
                             'south', 'east', 'west'}),
           'waterlogged': (False, {True, False})}),
    Block('andesite'),
    Block('polished_andesite'),
    Block('ancient_debris'),
    Block('anvil',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('chipped_anvil',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('damaged_anvil',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('azalea'),
    Block('flowering_azalea'),
    Block('bamboo',
          {'age': (0, {0, 1}),
           'leaves': ('none', {'none', 'small', 'large'}),
           'stage': (0, {0, 1})}),
    Block('barrel',
          {'facing': ('north', {'down', 'east', 'north',
                                'south', 'up', 'west'}),
           'open': (False, {True, False})}),
    Block('barrier'),
    Block('basalt',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('polished_basalt',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('smooth_basalt',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('beacon'),
    Block('white_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('orange_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('magenta_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('light_blue_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('yellow_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('lime_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('pink_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('gray_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('light_gray_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('cyan_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('purple_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('blue_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('brown_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('green_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('red_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('black_bed',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'occupied': (False, {True, False}),
           'part': ('foot', {'foot', 'head'})}),
    Block('bedrock'),
    Block('bee_nest',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'honey_level': (0, {0, 1, 2, 3, 4, 5})}),
    Block('beehive',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'honey_level': (0, {0, 1, 2, 3, 4, 5})}),
    Block('beetroots',
          {'age': (0, {0, 1, 2, 3})}),
    Block('bell',
          {'attachment': ('floor', {'ceiling', 'double_wall',
                                    'floor', 'single_wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('big_dripleaf',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'tilt': ('none', {'full', 'none', 'partial', 'unstable'}),
           'waterlogged': (False, {True, False})}),
    Block('big_dripleaf_stem',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (False, {True, False})}),
    Block('blackstone'),
    Block('blast_furnace',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False})}),
    Block('amethyst_block'),
    Block('coal_block'),
    Block('copper_block'),
    Block('exposed_copper'),
    Block('weathered_copper'),
    Block('oxidized_copper'),
    Block('cut_copper'),
    Block('exposed_cut_copper'),
    Block('weathered_cut_copper'),
    Block('oxidized_cut_copper'),
    Block('waxed_copper_block'),
    Block('waxed_exposed_copper'),
    Block('waxed_weathered_copper'),
    Block('waxed_oxidized_copper'),
    Block('waxed_cut_copper'),
    Block('waxed_exposed_cut_copper'),
    Block('waxed_weathered_cut_copper'),
    Block('waxed_oxidized_cut_copper'),
    Block('diamond_block'),
    Block('emerald_block'),
    Block('gold_block'),
    Block('lapis_block'),
    Block('netherite_block'),
    Block('quartz_block'),
    Block('chiseled_quartz_block'),
    Block('quartz_pillar',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('quartz_bricks'),
    Block('raw_copper_block'),
    Block('raw_gold_block'),
    Block('raw_iron_block'),
    Block('redstone_block'),
    Block('blue_ice'),
    Block('bone_block'),
    Block('bookshelf'),
    Block('brewing_stand'),
    Block('bricks'),
    Block('bubble_column',
          {'drag': (True, {True, False})}),
    Block('budding_amethyst'),
    Block('stone_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('oak_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('sprue_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('birch_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('jungle_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('acacia_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('dark_oak_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('mangrove_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('crimson_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('warped_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('polished_blackstone_button',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('cactus',
          {'age': (0, {*range(16)})}),
    Block('cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6})}),
    Block('candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('white_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('orange_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('magenta_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('light_blue_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('yellow_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('lime_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('pink_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('gray_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('light_gray_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('cyan_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('purple_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('blue_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('brown_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('green_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('red_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('black_candle_cake',
          {'bites': (0, {0, 1, 2, 3, 4, 5, 6}),
           'lit': (False, {True, False})}),
    Block('calcite'),
    Block('campfire',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (True, {True, False}),
           'signal_fire': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('soul_campfire',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (True, {True, False}),
           'signal_fire': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('white_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('orange_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('magenta_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('light_blue_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('yellow_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('lime_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('pink_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('gray_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('light_gray_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('cyan_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('purple_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('blue_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('brown_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('green_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('red_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('black_candle',
          {'candles': (1, {1, 2, 3, 4}),
           'lit': (True, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('white_carpet'),
    Block('orange_carpet'),
    Block('magenta_carpet'),
    Block('light_blue_carpet'),
    Block('yellow_carpet'),
    Block('lime_carpet'),
    Block('pink_carpet'),
    Block('gray_carpet'),
    Block('light_gray_carpet'),
    Block('cyan_carpet'),
    Block('purple_carpet'),
    Block('blue_carpet'),
    Block('brown_carpet'),
    Block('green_carpet'),
    Block('red_carpet'),
    Block('black_carpet'),
    Block('carrots',
          {'age': (0, {*range(8)})}),
    Block('cartography_table'),
    Block('cauldron'),
    Block('lava_cauldron',
          {'level': (0, {0, 1, 2, 3})}),
    Block('powder_snow_cauldron',
          {'level': (0, {0, 1, 2, 3})}),
    Block('water_cauldron',
          {'level': (0, {0, 1, 2, 3})}),
    Block('chain',
          {'waterlogged': (False, {True, False}),
           'axis': ('y', {'x', 'y', 'z'})}),
    Block('chest',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'type': ('single', {'left', 'right', 'single'}),
           'waterlogged': (False, {True, False})}),
    Block('chiseled_deepslate'),
    Block('chorus_flower',
          {'age': (0, {0, 1, 2, 3, 4, 5})}),
    Block('clay'),
    Block('coal_ore'),
    Block('deepslate_coal_ore'),
    Block('coarse_dirt'),
    Block('cobbled_deepslate'),
    Block('cobblestone'),
    Block('cobweb'),
    Block('cocoa',
          {'age': (0, {0, 1, 2}),
           'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('composter',
          {'level': (0, {*range(9)})}),
    Block('white_concrete'),
    Block('orange_concrete'),
    Block('magenta_concrete'),
    Block('light_blue_concrete'),
    Block('yellow_concrete'),
    Block('lime_concrete'),
    Block('pink_concrete'),
    Block('gray_concrete'),
    Block('light_gray_concrete'),
    Block('cyan_concrete'),
    Block('purple_concrete'),
    Block('blue_concrete'),
    Block('brown_concrete'),
    Block('green_concrete'),
    Block('red_concrete'),
    Block('black_concrete'),
    Block('white_concrete_powder'),
    Block('orange_concrete_powder'),
    Block('magenta_concrete_powder'),
    Block('light_blue_concrete_powder'),
    Block('yellow_concrete_powder'),
    Block('lime_concrete_powder'),
    Block('pink_concrete_powder'),
    Block('gray_concrete_powder'),
    Block('light_gray_concrete_powder'),
    Block('cyan_concrete_powder'),
    Block('purple_concrete_powder'),
    Block('blue_concrete_powder'),
    Block('brown_concrete_powder'),
    Block('green_concrete_powder'),
    Block('red_concrete_powder'),
    Block('black_concrete_powder'),
    Block('conduit',
          {'waterlogged': (True, {True, False})}),
    Block('copper_ore'),
    Block('deepslate_copper_ore'),
    Block('tube_coral',
          {'waterlogged': (True, {True, False})}),
    Block('brain_coral',
          {'waterlogged': (True, {True, False})}),
    Block('bubble_coral',
          {'waterlogged': (True, {True, False})}),
    Block('fire_coral',
          {'waterlogged': (True, {True, False})}),
    Block('horn_coral',
          {'waterlogged': (True, {True, False})}),
    Block('dead_tube_coral',
          {'waterlogged': (True, {True, False})}),
    Block('dead_brain_coral',
          {'waterlogged': (True, {True, False})}),
    Block('dead_bubble_coral',
          {'waterlogged': (True, {True, False})}),
    Block('dead_fire_coral',
          {'waterlogged': (True, {True, False})}),
    Block('dead_horn_coral',
          {'waterlogged': (True, {True, False})}),
    Block('tube_coral_block'),
    Block('brain_coral_block'),
    Block('bubble_coral_block'),
    Block('fire_coral_block'),
    Block('horn_coral_block'),
    Block('dead_tube_coral_block'),
    Block('dead_brain_coral_block'),
    Block('dead_bubble_coral_block'),
    Block('dead_fire_coral_block'),
    Block('dead_horn_coral_block'),
    Block('tube_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('brain_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('bubble_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('fire_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('horn_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('dead_tube_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('dead_brain_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('dead_bubble_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('dead_fire_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('dead_horn_coral_fan',
          {'waterlogged': (True, {True, False})}),
    Block('tube_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('brain_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('bubble_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('fire_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('horn_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('dead_tube_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('dead_brain_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('dead_bubble_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('dead_fire_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('dead_horn_coral_wall_fan',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (True, {True, False})}),
    Block('crafting_table'),
    Block('crying_obsidian'),
    Block('daylight_detector',
          {'inverted': (False, {True, False}),
           'power': (0, {*range(16)})}),
    Block('dead_bush'),
    Block('deepslate'),
    Block('deepslate_bricks'),
    Block('cracked_deepslate_bricks'),
    Block('deepslate_tiles'),
    Block('cracked_deepslate_tiles'),
    Block('detector_rail',
          {'powered': (False, {True, False}),
           'shape': ('north_south', {'east_west', 'north_south', 'ascending_east',
                                     'ascending_north', 'ascending_south', 'ascending_west'}),
           'waterlogged': (False, {True, False})}),
    Block('diamond_ore'),
    Block('deepslate_diamond_ore'),
    Block('diorite'),
    Block('polished_diorite'),
    Block('dirt'),
    Block('dirt_path'),
    Block('dispenser',
          {'facing': ('north', {'down', 'east', 'north',
                                'south', 'up', 'west'}),
           'triggered': (False, {True, False})}),
    Block('iron_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('wooden_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('spruce_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('birch_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('jungle_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('acacia_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('dark_oak_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('crimson_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('warped_door',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'hinge': ('left', {'left', 'right'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('dragon_egg'),
    Block('dried_kelp_block'),
    Block('dripstone_block'),
    Block('dropper',
          {'facing': ('north', {'down', 'east', 'north',
                                'south', 'up', 'west'}),
           'triggered': (False, {True, False})}),
    Block('emerald_ore'),
    Block('deepslate_emerald_ore'),
    Block('enchanting_table'),
    Block('end_portal_frame',
          {'eye': (False, {True, False}),
           'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('end_rod',
          {'facing': ('north', {'down', 'east', 'north',
                                'south', 'up', 'west'})}),
    Block('end_stone'),
    Block('end_stone_bricks'),
    Block('ender_chest',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (False, {True, False})}),
    Block('farmland',
          {'moisture': (0, {*range(8)})}),
    Block('oak_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('spruce_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('birch_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('jungle_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('acacia_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('dark_oak_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('mangrove_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('crimson_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('warped_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('nether_brick_fence',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('oak_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('spruce_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('birch_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('jungle_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('acacia_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('dark_oak_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('mangrove_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('crimson_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('warped_fence_gate',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'in_wall': (False, {True, False}),
           'open': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('fire',
          {'age': (0, {*range(16)}),
           'east': (False, {True, False}),
           'south': (False, {True, False}),
           'west': (False, {True, False}),
           'north': (False, {True, False}),
           'up': (False, {True, False})}),
    Block('fletching_table'),
    Block('dandelion'),
    Block('poppy'),
    Block('blue_orchid'),
    Block('allium'),
    Block('azure_bluet'),
    Block('red_tulip'),
    Block('orange_tulip'),
    Block('white_tulip'),
    Block('pink_tulip'),
    Block('oxeye_daisy'),
    Block('cornflower'),
    Block('lily_of_the_valley'),
    Block('wither_rose'),
    Block('sunflower',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('lilac',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('rose_bush',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('peony',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('pearlescent_froglight',
          {'axids': ('y', {'x', 'y', 'z'})}),
    Block('verdant_froglight',
          {'axids': ('y', {'x', 'y', 'z'})}),
    Block('ochre_froglight',
          {'axids': ('y', {'x', 'y', 'z'})}),
    Block('frosted_ice',
          {'age': (0, {0, 1, 2, 3})}),
    Block('crimson_fungus'),
    Block('warped_fungus'),
    Block('furnace',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False})}),
    Block('gilded_blackstone'),
    Block('glass'),
    Block('white_stained_glass'),
    Block('orange_stained_glass'),
    Block('magenta_stained_glass'),
    Block('light_blue_stained_glass'),
    Block('yellow_stained_glass'),
    Block('lime_stained_glass'),
    Block('pink_stained_glass'),
    Block('gray_stained_glass'),
    Block('light_gray_stained_glass'),
    Block('cyan_stained_glass'),
    Block('purple_stained_glass'),
    Block('blue_stained_glass'),
    Block('brown_stained_glass'),
    Block('green_stained_glass'),
    Block('red_stained_glass'),
    Block('black_stained_glass'),
    Block('glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('white_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('orange_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('magenta_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('light_blue_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('yellow_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('lime_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('pink_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('gray_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('light_gray_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('cyan_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('purple_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('blue_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('brown_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('green_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('red_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('black_stained_glass_pane',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('white_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('orange_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('magenta_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('light_blue_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('yellow_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('lime_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('pink_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('gray_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('light_gray_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('cyan_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('purple_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('blue_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('brown_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('green_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('red_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('black_glazed_terracotta',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('cave_vines',
          {'berries': (False, {True, False}),
           'age': (0, {*range(26)})}),
    Block('cave_vines_plant',
          {'berries': (False, {True, False})}),
    Block('glow_lichen',
          {'east': (False, {True, False}),
           'south': (False, {True, False}),
           'west': (False, {True, False}),
           'north': (False, {True, False}),
           'up': (False, {True, False}),
           'down': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('glowstone'),
    Block('gold_ore'),
    Block('deepslate_gold_ore'),
    Block('granite'),
    Block('polished_granite'),
    Block('grass'),
    Block('fern'),
    Block('tall_grass',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('large_fern',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('grass_block',
          {'snowy': (False, {True, False})}),
    Block('gravel'),
    Block('grindstone',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('hanging_roots'),
    Block('hay_block',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('skeleton_skull',
          {'rotation': (0, {*range(16)})}),
    Block('wither_skeleton_skull',
          {'rotation': (0, {*range(16)})}),
    Block('zombie_head',
          {'rotation': (0, {*range(16)})}),
    Block('creeper_head',
          {'rotation': (0, {*range(16)})}),
    Block('skeleton_wall_skull',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('wither_skeleton_wall_skull',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('zombie_wall_head',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('creeper_wall_head',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('dragon_wall_head',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('honey_block'),
    Block('honeycomb_block'),
    Block('hopper',
          {'enabled': (True, {True, False}),
           'facing': ('down', {'east', 'south', 'west', 'north', 'down'})}),
    Block('ice'),
    Block('infested_stone'),
    Block('infested_cobblestone'),
    Block('infested_stone_bricks'),
    Block('infested_cracked_stone_bricks'),
    Block('infested_mossy_stone_bricks'),
    Block('infested_chiseled_stone_bricks'),
    Block('infested_deepslate'),
    Block('iron_bars',
          {'east', (False, {True, False}),
           'south', (False, {True, False}),
           'west', (False, {True, False}),
           'north', (False, {True, False}),
           'waterlogged', (False, {True, False})}),
    Block('iron_ore'),
    Block('deepslate_iron_ore'),
    Block('jukebox',
          {'has_record': (False, {True, False})}),
    Block('kelp',
          {'age': (0, {*range(26)})}),
    Block('kelp_plant'),
    Block('ladder',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'waterlogged': (False, {True, False})}),
    Block('lantern',
          {'hanging': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('soul_lantern',
          {'hanging': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('lapis_ore'),
    Block('deepslate_lapis_ore'),
    Block('flowing_lava',
          {'level', (0, {*range(16)})}),
    Block('lava'),
    Block('oak_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('spruce_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('birch_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('jungle_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('acacia_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('dark_oak_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mangrove_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('azalea_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('flowering_azalea_leaves',
          {'distance': (7, range(1, 7)),
           'persistent': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('lever',
          {'face': ('wall', {'ceiling', 'floor', 'wall'}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('lightning_rod',
          {'facing': ('north', {'east', 'south', 'west',
                                'north', 'up', 'down'}),
           'powered': (False, {True, False})}),
    Block('lily_pad'),
    Block('lodestone'),
    Block('oak_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('spruce_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('birch_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('jungle_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('acacia_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('dark_oak_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('mangrove_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('crimson_stem',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('warped_stem',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_oak_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_spruce_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_birch_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_jungle_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_acacia_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_dark_oak_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_mangrove_log',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_crimson_stem',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_warped_stem',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('loom',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('magma_block'),
    Block('mangrove_roots',
          {'waterlogged': (False, {True, False})}),
    Block('melon'),
    Block('melon_stem',
          {'age': (0, {*range(8)})}),
    Block('attached_melon_stem',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('moss_block'),
    Block('mossy_cobblestone'),
    Block('mud'),
    Block('mud_bricks'),
    Block('muddy_mangrove_roots'),
    Block('brown_mushroom'),
    Block('red_mushroom'),
    Block('brown_mushroom_block',
          {'east': (True, {True, False}),
           'south': (True, {True, False}),
           'west': (True, {True, False}),
           'north': (True, {True, False}),
           'up': (True, {True, False}),
           'down': (True, {True, False})}),
    Block('red_mushroom_block',
          {'east': (True, {True, False}),
           'south': (True, {True, False}),
           'west': (True, {True, False}),
           'north': (True, {True, False}),
           'up': (True, {True, False}),
           'down': (True, {True, False})}),
    Block('mushroom_stem',
          {'east': (True, {True, False}),
           'south': (True, {True, False}),
           'west': (True, {True, False}),
           'north': (True, {True, False}),
           'up': (True, {True, False}),
           'down': (True, {True, False})}),
    Block('mycelium',
          {'snowy': (False, {False, True})}),
    Block('nether_bricks'),
    Block('red_nether_bricks'),
    Block('cracked_nether_bricks'),
    Block('chiseled_nether_bricks'),
    Block('nether_gold_ore'),
    Block('nether_quartz_ore'),
    Block('nether_sprouts'),
    Block('nether_wart',
          {'age': (0, {*range(4)})}),
    Block('nether_wart_block'),
    Block('warped_wart_block'),
    Block('netherrack'),
    Block('note_block',
          {'instrument': ('harp', {
              'banjo', 'basedrum', 'base', 'bell', 'bit',
              'chime', 'cow_bell', 'didgeridoo', 'flute',
              'guitar', 'harp', 'hat', 'iron_xylophone',
              'pling', 'snare', 'xylophone'}),
           'note': (0, {*range(25)}),
           'powered': (False, {False, True})}),
    Block('crimson_nylium'),
    Block('warped_nylium'),
    Block('observer',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'powered': (False, {True, False})}),
    Block('obsidian'),
    Block('packed_ice'),
    Block('packed_mud'),
    Block('piston',
          {'extended': (False, {True, False}),
           'facing': ('north', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('sticky_piston',
          {'extended': (False, {True, False}),
           'facing': ('north', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('piston_head'),
    Block('oak_planks'),
    Block('spruce_planks'),
    Block('birch_planks'),
    Block('jungle_planks'),
    Block('acacia_planks'),
    Block('dark_oak_planks'),
    Block('mangrove_planks'),
    Block('crimson_planks'),
    Block('warped_planks'),
    Block('podzol',
          {'snowy': (False, {True, False})}),
    Block('pointed_dripstone',
          {'thickness': ('tip', {'tip_merge', 'tip', 'frustnum', 'middle', 'base'}),
           'vertical_direction': ('up', {'up', 'down'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone'),
    Block('chiseled_polished_blackstone'),
    Block('polished_blackstone_bricks'),
    Block('cracked_polished_blackstone_bricks'),
    Block('polished_deepslate'),
    Block('potatoes',
          {'age': (0, {*range(8)})}),
    Block('powder_snow'),
    Block('powered_rail',
          {'powered': (False, {True, False}),
           'shape': ('north_south', {'east_west', 'north_south', 'ascending_east',
                                     'ascending_north', 'ascending_south', 'ascending_west'}),
           'waterlogged': (False, {True, False})}),
    Block('light_weighted_pressure_plate',
          {'powered': (False, {True, False}),
           'power': (0, {*range(16)})}),
    Block('heavy_weighted_pressure_plate',
          {'powered': (False, {True, False}),
           'power': (0, {*range(16)})}),
    Block('stone_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('polished_blackstone_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('oak_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('spruce_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('birch_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('jungle_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('acacia_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('dark_oak_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('mangrove_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('crimson_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('warped_pressure_plate',
          {'powered': (False, {True, False})}),
    Block('prismarine'),
    Block('prismarine_bricks'),
    Block('dark_prismarine'),
    Block('pumpkin'),
    Block('carved_pumpkin',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('pumpkin_stem',
          {'age': (0, {*range(8)})}),
    Block('attached_pumpkin_stem',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('purpur_block'),
    Block('purpur_pillar',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('rail',
          {'shape': ('north_south', {
              'east_west', 'north_east', 'north_south',
              'north_west', 'south_east', 'south_west',
              'ascending_east', 'ascending_north',
              'ascending_south', 'ascending_west'}),
           'waterlogged': (False, {True, False})}),
    Block('comparator',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'mode': ('compare', {'compare', 'subtract'}),
           'powered': (False, {True, False})}),
    Block('redstone_wire',
          {'east': ('none', {'none', 'side', 'up'}),
           'south': ('none', {'none', 'side', 'up'}),
           'west': ('none', {'none', 'side', 'up'}),
           'north': ('none', {'none', 'side', 'up'}),
           'power': (0, {*range(16)})}),
    Block('redstone_lamp',
          {'lit': (False, {True, False})}),
    Block('redstone_ore',
          {'lit': (False, {True, False})}),
    Block('deepslate_redstone_ore',
          {'lit': (False, {True, False})}),
    Block('repeater',
          {'delay': (1, {1, 2, 3, 4}),
           'facing': ('north', {'east', 'south', 'west', 'north'}),
           'locked': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('redstone_torch',
          {'lit': (False, {True, False})}),
    Block('redstone_wall_torch',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False})}),
    Block('reinforced_deepslate'),
    Block('respawn_anchor',
          {'charges': (0, {*range(5)})}),
    Block('rooted_dirt'),
    Block('crimson_roots'),
    Block('warped_roots'),
    Block('sand'),
    Block('red_sand'),
    Block('sandstone'),
    Block('cut_sandstone'),
    Block('chiseled_sandstone'),
    Block('smooth_sandstone'),
    Block('red_sandstone'),
    Block('cut_red_sandstone'),
    Block('chiseled_red_sandstone'),
    Block('smooth_red_sandstone'),
    Block('oak_sapling',
          {'stage': (0, {0, 1})}),
    Block('spruce_sapling',
          {'stage': (0, {0, 1})}),
    Block('birch_sapling',
          {'stage': (0, {0, 1})}),
    Block('jungle_sapling',
          {'stage': (0, {0, 1})}),
    Block('acacia_sapling',
          {'stage': (0, {0, 1})}),
    Block('dark_oak_sapling',
          {'stage': (0, {0, 1})}),
    Block('mangrove_propagule',
          {'age': (0, {*range(4)}),
           'hanging': (False, {True, False}),
           'stage': (0, {0, 1}),
           'waterlogged': (False, {True, False})}),
    Block('sculk'),
    Block('sculk_catalyst',
          {'bloom', (False, {True, False})}),
    Block('sculk_sensor',
          {'power': (0, {*range(16)}),
           'sculk_sensor_phase': ('cooldown', {'active', 'cooldown', 'inactive'}),
           'waterlogged': (False, {True, False})}),
    Block('sculk_shrieker',
          {'can_summon': (False, {True, False}),
           'shrieking': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('sculk_vein',
          {'east': (False, {True, False}),
           'south': (False, {True, False}),
           'west': (False, {True, False}),
           'north': (False, {True, False}),
           'up': (False, {True, False}),
           'down': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('sea_lantern'),
    Block('sea_pickle',
          {'pickles': (1, {1, 2, 3, 4}),
           'waterlogged': (True, {True, False})}),
    Block('seagrass'),
    Block('tall_seagrass',
          {'half': ('lower', {'lower', 'upper'})}),
    Block('shroomlight'),
    Block('shrub'),
    Block('shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('white_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('orange_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('magenta_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('light_blue_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('yellow_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('lime_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('pink_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('gray_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('light_gray_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('cyan_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('purple_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('blue_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('brown_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('green_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('red_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('black_shulker_box',
          {'facing': ('up', {'east', 'south', 'west', 'north', 'up', 'down'})}),
    Block('standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('spruce_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('birch_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('jungle_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('acacia_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('darkoak_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('crimson_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('warped_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mangrove_standing_sign',
          {'rotation': (0, {*range(16)}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('spruce_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('birch_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('jungle_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('acacia_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('darkoak_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('crimson_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('warped_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mangrove_wall_sign',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'lit': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('oak_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('spruce_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('birch_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('jungle_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('acacia_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('dark_oak_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('crimson_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('warped_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('stone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_stone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('granite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_granite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('diorite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_diorite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('andesite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_andesite_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_cobblestone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('stone_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_stone_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('end_stone_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('nether_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('red_nether_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('cut_sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('red_sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('cut_red_sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_red_sandstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('quartz_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_quartz_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('purpur_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('prismarine_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('prismarine_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('dark_prismarine_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('blackstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('exposed_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('weathered_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('oxidized_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_exposed_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_weathered_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_oxidized_cut_copper_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('cobbled_deepslate_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_deepslate_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_tile_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('mud_brick_slab',
          {'type': ('bottom', {'bottom', 'top', 'double'}),
           'waterlogged': (False, {True, False})}),
    Block('slime_block'),
    Block('small_dripleaf',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('lower', {'lower', 'upper'}),
           'waterlogged': (False, {True, False})}),
    Block('smithing_table'),
    Block('smooth_quartz'),
    Block('smooth_stone'),
    Block('snow',
          {'layers': (1, {*range(1, 9)})}),
    Block('snow_block'),
    Block('soul_sand'),
    Block('soul_soil'),
    Block('spawner'),
    Block('sponge'),
    Block('wet_sponge'),
    Block('spore_blossom'),
    Block('oak_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('spruce_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('birch_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('jungle_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('acacia_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('dark_oak_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('mangrove_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('crimson_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('warped_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('stone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('granite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_granite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('diorite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_diorite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('andesite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_andesite_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('cobblestone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_cobblestone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('stone_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_stone_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('end_stone_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('nether_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('red_nether_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('sandstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_sandstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('red_sandstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_red_sandstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('quartz_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('smooth_quartz_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('purpur_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('prismarine_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('prismarine_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('dark_prismarine_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('blackstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('exposed_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('weathered_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('oxidized_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_exposed_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_weathered_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('waxed_oxidized_cut_copper_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('cobbled_deepslate_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('polished_deepslate_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_tile_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('mud_brick_stairs',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'shape': ('straight', {'inner_left', 'inner_right', 'outer_left', 'outer_right', 'straight'}),
           'waterlogged': (False, {True, False})}),
    Block('stone'),
    Block('stone_bricks'),
    Block('cracked_stone_bricks'),
    Block('mossy_stone_bricks'),
    Block('chiseled_stone_bricks'),
    Block('stonecutter'),
    Block('tripwire'),
    Block('tripwire',
          {'east': (False, {True, False}),
           'south': (False, {True, False}),
           'west': (False, {True, False}),
           'north': (False, {True, False}),
           'attached': (False, {True, False}),
           'disarmed': (False, {True, False}),
           'powered': (False, {True, False})}),
    Block('sugar_cane',
          {'age': (0, {*range(16)})}),
    Block('sweet_berry_bush',
          {'age': (0, {*range(4)})}),
    Block('target',
          {'power': (0, {*range(16)})}),
    Block('terracotta'),
    Block('white_terracotta'),
    Block('orange_terracotta'),
    Block('magenta_terracotta'),
    Block('light_blue_terracotta'),
    Block('yellow_terracotta'),
    Block('lime_terracotta'),
    Block('pink_terracotta'),
    Block('gray_terracotta'),
    Block('light_gray_terracotta'),
    Block('cyan_terracotta'),
    Block('purple_terracotta'),
    Block('blue_terracotta'),
    Block('brown_terracotta'),
    Block('green_terracotta'),
    Block('red_terracotta'),
    Block('black_terracotta'),
    Block('tinted_glass'),
    Block('tnt'),
    Block('torch'),
    Block('soul_torch'),
    Block('wall_torch',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('soul_wall_torch',
          {'facing': ('north', {'east', 'south', 'west', 'north'})}),
    Block('iron_trapdoor',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'half': ('bottom', {'bottom', 'top'}),
           'open': (False, {True, False}),
           'powered': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('trapped_chest',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'type': ('single', {'left', 'right', 'single'}),
           'waterlogged': (False, {True, False})}),
    Block('tripwire_hook',
          {'facing': ('north', {'east', 'south', 'west', 'north'}),
           'attached': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('tuff'),
    Block('turtle_egg',
          {'eggs': (1, {1, 2, 3, 4}),
           'batch': (0, {0, 1, 2})}),
    Block('twisting_vines',
          {'age': (0, {*range(26)})}),
    Block('twisting_vines_plant'),
    Block('vine',
          {'east': (False, {True, False}),
           'south': (False, {True, False}),
           'west': (False, {True, False}),
           'north': (False, {True, False}),
           'up': (False, {True, False})}),
    Block('cobblestone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_cobblestone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('stone_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mossy_stone_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('andesite_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('diorite_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('granite_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('sandstone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('red_sandstone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('prismarine_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('nether_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('red_nether_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('end_stone_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('blackstone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('polished_blackstone_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('cobbled_deepslate_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('polished_deepslate_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('deepslate_tile_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('mud_brick_wall',
          {'east': ('none', {'low', 'none', 'tall'}),
           'south': ('none', {'low', 'none', 'tall'}),
           'west': ('none', {'low', 'none', 'tall'}),
           'north': ('none', {'low', 'none', 'tall'}),
           'up': (False, {True, False}),
           'waterlogged': (False, {True, False})}),
    Block('flowing_water',
          {'level', (0, {*range(16)})}),
    Block('water'),
    Block('weeping_vines',
          {'age': (0, {*range(26)})}),
    Block('weeping_vines_plant'),
    Block('wheat',
          {'age': (0, {*range(8)})}),
    Block('oak_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('spruce_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('birch_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('jungle_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('acacia_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('dark_oak_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('mangrove_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('crimson_hyphae',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('warped_hyphae',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_oak_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_spruce_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_birch_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_jungle_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_acacia_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_dark_oak_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_mangrove_wood',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_crimson_hyphae',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('stripped_warped_hyphae',
          {'axis': ('y', {'x', 'y', 'z'})}),
    Block('white_wool'),
    Block('orange_wool'),
    Block('magenta_wool'),
    Block('light_blue_wool'),
    Block('yellow_wool'),
    Block('lime_wool'),
    Block('pink_wool'),
    Block('gray_wool'),
    Block('light_gray_wool'),
    Block('cyan_wool'),
    Block('purple_wool'),
    Block('blue_wool'),
    Block('brown_wool'),
    Block('green_wool'),
    Block('red_wool'),
    Block('black_wool'),
]
