TICKS_PER_SEC = 60

CHUNK_SIZE = 16

WALKING_SPEED = 4.317
SPRINTING_SPEED = 5.612
SNEAKING_SPEED = 1.3
FLYING_SPEED = 11
FLYING_Y_SPEED = 3
FLYING_SPRINT_SPEED = 22

GRAVITY = 20
MAX_JUMP_HEIGHT = 1.25
TERMINAL_VELOCITY = 50

PLAYER_HEIGHT = 2

TEXTURE_PATH = 'texture.png'
